#!/bin/bash

ini() {
    # Upgrade server and install requirement.
    sudo apt -y update && apt -y upgrade && apt -y autoremove
    sudo apt -y install python3-pip python3-dev build-essential libssl-dev libffi-dev python3-setuptools python3.8-venv python3.8-dev gcc
    # Clone the project and create Python virtual environment(venv)
    cd /root && git clone https://github.com/cattomgithub/ServerMonitor.git
    cd ServerMonitor && mkdir env
    python3 -m venv /root/ServerMonitor/env
    # shellcheck source=/dev/null
    source /root/ServerMonitor/env/bin/activate
    # Check Python version > 3
    if [[ "$(python -V)" =~ "2" ]]; then
        exit 1
    fi
    # Install requirement by pip.
    pip install -r requirements.txt
}

public() (
    # shellcheck source=/dev/null
    source /root/ServerMonitor/env/bin/activate
    # Collect static file.
    cd /root/nginx_data/monitor && mkdir static
    cd /root/ServerMonitor/ && python manage.py collectstatic
    # Create vassals of uwsgi
    cd /root/ServerMonitor/env/ && mkdir public_vassals
    sudo ln -s /root/ServerMonitor/uwsgi/public_uwsgi.ini /root/ServerMonitor/env/public_vassals/
    # Register public.uwsgi.service as a system service.
    sudo ln -s /root/ServerMonitor/systemd/public.uwsgi.service /etc/systemd/system/public.uwsgi.service
    sudo systemctl daemon-reload
    systemctl enable public.uwsgi.service
    systemctl start public.uwsgi.service
    # Copy params file of uwsgi to nginx work directory
)
