# Generated by Django 4.1 on 2022-08-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OSDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_ID', models.CharField(max_length=5)),
                ('Uptime_Day', models.CharField(max_length=10)),
                ('Uptime_Hour', models.CharField(max_length=10)),
                ('Uptime_Min', models.CharField(max_length=10)),
                ('Uptime_Sec', models.CharField(max_length=10)),
                ('CPU_Usage', models.CharField(max_length=10)),
                ('Memory_Usage', models.CharField(max_length=10)),
            ],
        ),
    ]
