# Generated by Django 4.1 on 2022-08-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osdetail',
            name='id',
        ),
        migrations.AlterField(
            model_name='osdetail',
            name='Server_ID',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
