# Generated by Django 4.1 on 2022-08-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0002_remove_osdetail_id_alter_osdetail_server_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osdetail',
            name='Uptime_Day',
            field=models.CharField(max_length=100),
        ),
    ]
