# Generated by Django 4.1 on 2022-08-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('server_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cpu_usage', models.CharField(max_length=5)),
                ('mem_usage', models.CharField(max_length=5)),
                ('load_avg', models.CharField(max_length=20)),
                ('uptime_day', models.IntegerField()),
                ('uptime_hour', models.IntegerField()),
                ('uptime_minute', models.IntegerField()),
                ('uptime_second', models.IntegerField()),
                ('Last_Update', models.DateTimeField(auto_now=True, verbose_name='date published')),
            ],
        ),
    ]
