# Generated by Django 4.1 on 2022-08-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_name',
            field=models.CharField(default='server_name', max_length=200),
        ),
    ]
