# Generated by Django 4.1 on 2022-08-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_server_server_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='Last_Update',
            field=models.DateTimeField(auto_now=True, verbose_name='last update'),
        ),
    ]
